server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/bootdo?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    url: jdbc:mysql://localhost:3306/bootdo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    timeout: 0
    password:
      jedis:
        # 设置都是默认值，可以按需求设计
        pool:
          max-active: 8   # 可用连接实例的最大数目，默认值为8；如果赋值为-1，则表示不限制；
          max-idle: 8     # 控制一个pool最多有多少个状态为idle(空闲的)的redis实例，默认值也是8。
          max-wait: -1    # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。
          min-idle: 0     # 控制一个pool最少有多少个状态为idle(空闲的)的redis实例，默认值为0。